---
# title: "Aufgabe 2: Point Pattern Analysis"
# author: "Christa Rohrbach"
# date: "2023-03-25"
# bibliography: references.bib
# csl: harvard-educational-review.csl
output:
  bookdown::pdf_document2:
    toc: true
    number_sections: false
    latex_engine: xelatex
colorlinks: yes
urlcolor: blue
classoption: landscape
header-includes:
  \usepackage{fancyhdr,lastpage,multirow,caption}
  \fancypagestyle{plain}{
    \fancyhf{}
    \fancyhead[L]{Master Thesis results}
    \fancyhead[R]{Christa Rohrbach}
    \fancyfoot[R]{\thepage\  / \pageref{LastPage}}
  }
  \pagestyle{plain}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE
)

# Exponentialschreibweise erst ab 7-stelligen Zahlen
options(scipen=6, digits=4)

library(knitr)
library(kableExtra)
library(readr)
library(cowplot)
library(ggplot2)
library(sf)
library(terra)
library(tidyterra)
library(rnaturalearth)
library(rnaturalearthdata)
library(RColorBrewer)
library(dplyr)

# rgdal, rgeos and maptools retire by the end of 2023! use sf, stars and terra!

theme_set(theme_classic())
theme_update(
  panel.grid.major = element_line(colour = "transparent"),
  plot.title = element_text(size=6),
  #axis.title = element_text(size=10),
  #legend.title = element_text(size=8),
  axis.text = element_text(size=4),
  #axis.text.x = element_text(angle = 45, hjust=1)
  #panel.border = element_rect(color = "black", fill = NA, size = 0.1),
  axis.ticks = element_line(linewidth = 0.1),
  #axis.line.x = element_blank(),
  #axis.line.y = element_blank(),
  axis.line = element_line(linewidth = 0.1),
  axis.title = element_blank(),
  legend.title = element_text(size = 6),
  legend.text = element_text(size = 4),
  legend.key.size = unit(3, 'mm'),
  legend.box.spacing = unit(0, 'mm')
)
initial_theme <- theme_get()
```

```{r settings, results='hide'}
# Input data paths and configuration

# manual settings
workdir <- "C:/Users/Christa/Documents/Git/manuscript/data"
presence_gpkg <- "msculpturalis_20240408.gpkg"
cost_surface_name <- "msculpturalis_sdm_clip_rev_scaled100.tif"
script_run <- "msculp20240408_sdmrev100_95q_group"
script_run_1 <- "msculp20240408_sdmrev100_90q_group"

# dynamic settings
presence_gpkg_path <- file.path(workdir, presence_gpkg)
points_name <- gsub("\\.gpkg", "", presence_gpkg)
cost_surface_path <- file.path(workdir, cost_surface_name)

results_gpkg_path <- file.path(workdir, paste0(script_run, ".gpkg"))
paths_name <- paste0(script_run, "_paths")
paths_grouped_name <- paste0(script_run, "_paths_grouped")
points_thinned_grouped_name <- paste0(script_run, "_points_thinned_grouped")
exp_rate_path <- file.path(workdir, paste0(script_run, "_expansion_rates_plot_data.csv"))
sensitivity_path <- file.path(workdir, paste0(script_run, "_outlier_fence_test.csv"))

results_gpkg_path_1 <- file.path(workdir, paste0(script_run_1, ".gpkg"))
paths_name_1 <- paste0(script_run_1, "_paths")
paths_grouped_name_1 <- paste0(script_run_1, "_paths_grouped")
points_thinned_grouped_name_1 <- paste0(script_run_1, "_points_thinned_grouped")
exp_rate_path_1 <- file.path(workdir, paste0(script_run_1, "_expansion_rates_plot_data.csv"))
sensitivity_path_1 <- file.path(workdir, paste0(script_run_1, "_outlier_fence_test.csv"))
```

```{r data, results='hide'}
# Load data
cost_surface <- rast(cost_surface_path)
#NAflag(cost_surface) <- 0  # tbd: workaround to avoid NoData being plotted
site_bbox <- ext(cost_surface)
presence <- st_read(presence_gpkg_path, layer = points_name)
thinned_grouped <- st_read(results_gpkg_path, layer = points_thinned_grouped_name)
thinned_grouped_1 <- st_read(results_gpkg_path_1, layer = points_thinned_grouped_name_1)
lcp_orig <- st_read(results_gpkg_path, layer = paths_name)
lcp <- st_read(results_gpkg_path, layer = paths_grouped_name)
lcp_1 <- st_read(results_gpkg_path_1, layer = paths_grouped_name_1)
world <- st_transform(ne_countries(scale = "medium", returnclass = "sf"), crs(cost_surface))
countries <- st_crop(world, site_bbox)
graticules <- st_graticule(x = countries)
```

```{r basemap, results='hide'}
# Create basemap
basemap <- ggplot() +
  geom_sf(data = countries, fill = "#f7f7f7", color = "gray", linewidth = 0.1) +
  #coord_sf(datum = st_crs(cost_surface)) +
  geom_sf(data = graticules, color = "gray", linetype = "dashed", linewidth = 0.1)
```


# Input data

```{r inputplots, results='hide', fig.keep='all', out.width='\\textwidth', out.height='\\textheight', fig.align='top'}
# Create maps with cost rasters
cost_map <- ggplot() +
  geom_spatraster(data = cost_surface) +
  scale_fill_viridis_c(na.value = "transparent", direction = -1) +
  #geom_sf(data = countries, fill = "transparent", color = "gray", linewidth = 0.1) +
  geom_sf(data = graticules, color = "gray", linetype = "dashed", linewidth = 0.1) +
  coord_sf(expand = FALSE) +  # this removes white space between map and axes
  ggtitle(cost_surface_name)

points_map <- basemap +
  geom_sf(data = presence, size = 0.1, color = "blue") +
  coord_sf(expand = FALSE) +
  ggtitle(paste0(points_name, " | n = ", nrow(presence[presence$observation_year < 2024, ])))

points_thinned_map <- basemap +
  geom_sf(data = thinned_grouped, size = 0.1, color = "blue") +
  coord_sf(expand = FALSE) +
  ggtitle(paste0("Thinned to first presence per cell | n = ", nrow(thinned_grouped)))

plot_grid(cost_map, points_map, NULL, points_thinned_map)
```


# Sequential Least-Cost Modelling

```{r pathplots, results='hide', fig.keep='all', out.width='\\textwidth', out.height='\\textheight', fig.align='top'}
# Create a list to store maps for each year
all_maps_list <- list()

# Loop through years 2009 to 2023
for (year in 2009:2023) {
  # Create a list to store maps for the current year
  maps_list <- list()
  
  lcp1 <- basemap +
    geom_sf(data = presence[presence$observation_year == year, ], size = 0.1, color = "red") +
    geom_sf(data = lcp[lcp$destination_year == year, ], linewidth = 0.1, color = "red") +
    geom_sf(data = presence[presence$observation_year < year, ], size = 0.1, color = "#3b55ff") +
    geom_sf(data = lcp[lcp$destination_year < year, ], linewidth = 0.1, color = "#3b55ff") +
    coord_sf(expand = FALSE) +
    ggtitle(paste0(year, " | ", script_run))
  
  lcp2 <- basemap +
    geom_sf(data = presence[presence$observation_year == year, ], size = 0.1, color = "red") +
    geom_sf(data = lcp_1[lcp_1$destination_year == year, ], linewidth = 0.1, color = "red") +
    geom_sf(data = presence[presence$observation_year < year, ], size = 0.1, color = "#3b55ff") +
    geom_sf(data = lcp_1[lcp_1$destination_year < year, ], linewidth = 0.1, color = "#3b55ff") +
    coord_sf(expand = FALSE) +
    ggtitle(paste0(year, " | ", script_run_1))
  
  # Store the maps for the current year in the list
  maps_list[[as.character(year)]] <- plot_grid(lcp1, lcp2, ncol = 2)
  
  # Store the map list for the current year in the overall list
  all_maps_list[[as.character(year)]] <- maps_list
}

# Output the maps using cowplot
plot_grid(
  all_maps_list[[as.character(2009)]][[1]],
  all_maps_list[[as.character(2010)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2011)]][[1]],
  all_maps_list[[as.character(2012)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2013)]][[1]],
  all_maps_list[[as.character(2014)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2015)]][[1]],
  all_maps_list[[as.character(2016)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2017)]][[1]],
  all_maps_list[[as.character(2018)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2019)]][[1]],
  all_maps_list[[as.character(2020)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2021)]][[1]],
  all_maps_list[[as.character(2022)]][[1]],
  ncol = 1
)
plot_grid(
  all_maps_list[[as.character(2023)]][[1]],
  ncol = 1
)
```


# Forming groups

## Data distribution of accumulated cost

```{r acc_cost_summary}
paste0("n = ", nrow(lcp_orig))
summary(lcp_orig$accumulated_cost)
```

```{r acc_cost_hist, results='hide', fig.keep='all'}
ggplot(data = lcp_orig, aes(x = accumulated_cost)) + 
  geom_histogram(bins=50) +
  labs(
    title = paste0(paths_name, "\nDistribution of accumulated cost"),
    x = "Accumulated Cost",
    y = "Count"
  ) +
  theme_bw()

# Restore initial theme
theme_set(initial_theme)
```

## Sensitivity analysis of thresholds

```{r sensitivity, results='hide', fig.keep='all', fig.width=8, fig.height=5}
sensitivity_data <- read.csv(sensitivity_path_1)

ggplot(sensitivity_data, aes(x = quantile, y = num_groups)) +
  geom_point() +
  labs(
    #title = "Sensitivity analysis results",
    x = "Threshold as quantile",
    y = "Number of groups"
  ) +
  theme_bw() +
  theme(legend.position = "none")

# Restore initial theme
theme_set(initial_theme)
```

## Resulting groups

```{r groupplots, results='hide', fig.keep='all', out.width='\\textwidth', out.height='\\textheight', fig.align='top'}
# Create maps with groups
groups1 <- basemap +
  geom_sf(data = thinned_grouped[is.na(thinned_grouped$group_id), ],  size = 0.1, color = "black") +
  geom_sf(data = lcp, aes(color = as.factor(lcp$group_id)), linewidth = 0.1) +
  coord_sf(expand = FALSE) +
  guides(color = FALSE) +
  ggtitle(paste0("Groups | ", script_run))

groups2 <- basemap +
  geom_sf(data = thinned_grouped_1[is.na(thinned_grouped_1$group_id), ],  size = 0.1, color = "black") +
  geom_sf(data = lcp_1, aes(color = as.factor(lcp_1$group_id)), linewidth = 0.1) +
  coord_sf(expand = FALSE) +
  guides(color = FALSE) +
  ggtitle(paste0("Groups | ", script_run_1))

plot_grid(groups1, groups2)
```

# Expansion rate

```{r rateplots, results='hide', fig.keep='all', fig.width=8, fig.height=3}
plot_data <- read.csv(exp_rate_path)
plot_data_1 <- read.csv(exp_rate_path_1)

rate1 <- ggplot(plot_data, aes(x=year, y=max_distance, group=group_id, color=as.factor(group_id))) +
  geom_line() +
  geom_point() +
  labs(title=paste0("Expansion rate by group | ", script_run),
       x="Year",
       y="Max. distance to first presence in group [m]",
       color="Group ID") +
  scale_color_brewer(palette = "Set2") +
  theme_bw() +
  theme(legend.position = "none")

rate2 <- ggplot(plot_data_1, aes(x=year, y=max_distance, group=group_id, color=as.factor(group_id))) +
  geom_line() +
  geom_point() +
  labs(title=paste0("Expansion rate by group | ", script_run_1),
       x="Year",
       y="Max. distance to first presence in group [m]",
       color="Group ID") +
  scale_color_brewer(palette = "Set2") +
  theme_bw() +
  theme(legend.position = "none")  # Hide the legend

plot_grid(rate1, rate2)

# Restore initial theme
theme_set(initial_theme)
```
